AllCops:
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "db/**/*" # Sometimes database migrations are complex. Go figure.

Metrics/LineLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"

Metrics/MethodLength:
  Max: 12
  Exclude:
    - "db/**/*"

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  Exclude:
    - "spec/**/*"

Style/MultilineBlockLayout:
  Exclude:
    - "spec/**/*"

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - "db/migrate/*" # We often add extra spaces for alignment in migrations.

Style/StringLiterals:
  EnforcedStyle: double_quotes
